services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  ml-service:
    build: ./ml-service
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - ml-service
    volumes:
      - ./uploads:/app/uploads
      - ./rag:/app/rag
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongo-data:
